package com.phantask.notice.dto;

import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Response Data Transfer Object for notice information.
 * <p>
 * Contains all notice details returned to clients after creation,
 * retrieval, or update operations. Includes system-generated fields
 * such as ID and creation timestamp.
 * 
 * @author PhanTask Team
 * @version 1.0
 * @since 2025-12-25
 */
@Data
public class NoticeResponse {

	/**
	 * Unique identifier for the notice.
	 * Auto-generated by the database.
	 */
	private Long id;

	/**
	 * The title of the notice.
	 */
	private String title;

	/**
	 * The content/body of the notice.
	 */
	private String content;

	/**
	 * The name of the person or department that posted the notice.
	 * Example: "HR_DEPARTMENT", "ADMIN", "IT_TEAM"
	 */
	private String postedBy;

	/**
	 * The priority level of the notice.
	 * Possible values: "URGENT", "IMPORTANT", "GENERAL"
	 */
	private String priority;

	/**
	 * List of role names that can view this notice.
	 * Example: ["HR", "TECHNICAL", "ACCOUNTS"]
	 */
	private List<String> targetRoles;

	/**
	 * Timestamp when the notice was created.
	 * Automatically set by the system upon creation.
	 */
	private LocalDateTime createdAt;
}
